site_name: Compose CodeView
site_description: Beautiful Syntax Highlighting for your Compose apps.
site_url: 'https://github.com/komodgn/compose-codeview'
edit_uri: 'tree/main/docs/'
remote_branch: gh-pages

theme:
  name: 'material'
  language: 'en'
  icon:
    logo: material/asterisk
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - content.code.copy

repo_name: 'Compose CodeView'
repo_url: 'https://github.com/komodgn/compose-codeview'

nav:
  - 'Overview': index.md
  - 'Setup': setup.md
  - 'CodeView':
      - 'Overview': codeview/overview.md
      - 'Language Support': codeview/languages.md
  - 'CodeEditor':
      - 'Overview': codeeditor/overview.md

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - macros
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/komodgn/compose-codeview

copyright: '&copy; 2026 komodgn'